# Generated by Django 6.0.7 on 2026-08-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_transaction_external_id_per_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='external_id',
        ),
    ]
